name = "china-detective-agency"
type = "javascript"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "china-detective-agency-prod"

[build]
command = "pnpm build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx", "src/**/*.css"]

[build.upload]
format = "service-worker"

[[routes]]
pattern = "*"
zone_name = ""
